services:
  coffeeshop-app:
    container_name: coffeeshop-app

    build:
      context: .
      dockerfile: Dockerfile

    image: coffeeshop-recommendation:latest

    restart: unless-stopped

    ports:
      - "5000:5000"

    tty: true
    stdin_open: true

    networks:
      - coffeeshop-network

networks:
  coffeeshop-network:
    driver: bridge